CREATE TABLE USER (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(35) NOT NULL,
  POSTCODE VARCHAR(8) NOT NULL,

);

CREATE TABLE EXERCISE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPTION VARCHAR(255),
  LEVEL BIGINT
);

CREATE TABLE USER_EXERCISE_LOG (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT,
  EXERCISE_ID BIGINT,
  DATE DATE NOT NULL
);

ALTER TABLE USER_EXERCISE_LOG ADD FOREIGN KEY (USER_ID) REFERENCES USER(ID);
ALTER TABLE USER_EXERCISE_LOG ADD FOREIGN KEY (EXERCISE_ID) REFERENCES EXERCISE(ID);
CREATE INDEX IDX_USER_ID ON USER(ID);
CREATE INDEX IDX_EXERCISE_ID ON EXERCISE(ID);
CREATE INDEX IDX_USER_EXERCISE_LOG_ID ON USER_EXERCISE_LOG(USER_ID);